# -*- coding: utf-8 -*-
"""Soil_Classification_230242300.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18cGa86eVrrU_bxupDKwX0b8UsUFiLY7i
"""

### Python codeblock to execute in ArcGIS Pro field calculator
# 230242300
# 18/8/24
# Python script to classify Danish soil data, value based on United States Department of Agriculture (1987)
# Soil mechanics Level 1 Module 3 USDA Soil Textural Classification Study Guide.
# Adapted from (Pappas, 2022).

typeID(!Clay!, !Sand1!, !Silt1!)

def typeID(clay, sand, silt):
    if (sand > 85 and (silt + (1.5 * clay)) <= 15):
        return "sand"
    elif (sand > 70 and sand <= 85 and (silt + (1.5 * clay)) > 15) or (sand > 85 and (silt + (2 * clay)) <= 30):
        return "loamy sand"
    elif (clay >= 7 and clay <= 20 and sand > 52 and (silt + 2 * clay) > 30) or (clay < 7 and silt < 50 and sand > 43 and sand <= 52):
        return "sandy loam"
    elif (clay >= 7 and clay <= 27 and silt >= 28 and silt < 50 and sand <= 52):
        return "loam"
    elif (silt >= 50 and (clay >= 12 and clay < 27)) or (silt >= 50 and silt < 80 and clay < 12):
        return "silt loam"
    elif (silt >= 80 and clay < 12):
        return "silt"
    elif (clay >= 20 and clay < 35 and silt < 28 and sand > 45):
        return "sandy clay loam"
    elif (clay >= 27 and clay < 40 and sand > 20 and sand <= 45):
        return "clay loam"
    elif (clay >= 27 and clay < 40 and sand <= 20):
        return "silty clay loam"
    elif (clay >= 35 and sand <= 45):
        return "sandy clay"
    elif (clay >= 40 and silt >= 40):
        return "silty clay"
    elif (clay >= 40 and sand <= 45 and silt < 40):
        return "clay"
    return None